name: Metrics
on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 0 * * *" # At 00:00 daily
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: denysdovhan
          template: classic
<<<<<<< HEAD
          # base: header, activity, community, repositories, metadata
=======
          base: header, activity, community, repositories, metadata
>>>>>>> 665383a919bf120d57b1ead8d33f95e816507daa
          filename: github-metrics.svg