name: Metrics
on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 0 * * *" # At 00:00 daily
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: denysdovhan
          template: classic
          filename: github-metrics.svg